name: Deploy Pipeline
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: 'projects/70756149774/locations/global/workloadIdentityPools/github-actions/providers/github-repos'
        service_account: 'hshn-devsecops-service-account@hs-heilbronn-devsecops.iam.gserviceaccount.com'
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}

    - name: Configure gcloud
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud auth configure-docker gcr.io

    - name: Build Docker image
      run: |
        IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/note-api:${{ github.sha }}
        docker build --platform linux/amd64 -t $IMAGE .

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository }}:${{ github.sha }}

    - id: deploy
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: note-api-${{ github.repository_owner }}
        source: "."
        region: europe-west3
        env_vars: BACKEND=memory

    - name: Use output
      run: curl "${{ steps.deploy.outputs.url }}"